import type {
  Conversation,
  UsageStats,
  UserUsage,
  PropertyUsage,
  ClientUsage,
  AuditConversation,
  ChatMessage,
  BetaClient,
  BetaOverview,
  AllotmentChange,
} from "./types"

export const sampleConversations: Conversation[] = [
  {
    id: "conv-1",
    title: "Lease renewal best practices",
    preview: "What are the best practices for structuring renewal offers?",
    timestamp: "Mar 10, 2026 2:34 PM",
    messageCount: 6,
    tokensUsed: 2450,
    messages: [
      { id: "m1", sender: "user", content: "What are the best practices for structuring renewal offers to maximize retention?", timestamp: "2:30 PM" },
      { id: "m2", sender: "assistant", content: "Great question! Here are the key best practices for renewal offers:\n\n1. **Start early** — Send the initial offer 90-120 days before expiration to give residents time to consider.\n2. **Tiered pricing** — Offer 2-3 lease term options (e.g., 6-month, 12-month, 15-month) with the best rate on longer terms.\n3. **Personalize the offer** — Reference the resident's tenure and payment history.\n4. **Highlight value** — Include any property improvements or amenity updates since their last lease.\n5. **Create urgency** — Set a response deadline (typically 30 days) with a clear call-to-action.", timestamp: "2:30 PM" },
      { id: "m3", sender: "user", content: "What's a reasonable rent increase percentage for renewals?", timestamp: "2:32 PM" },
      { id: "m4", sender: "assistant", content: "The optimal renewal increase depends on several factors:\n\n- **Market average**: Most markets see 3-5% annual increases\n- **Resident tenure**: Long-term residents (3+ years) may warrant a smaller increase to retain them\n- **Vacancy cost**: A 30-day vacancy typically costs more than a 2-3% concession\n- **Market comps**: Compare your renewal rate to new lease rates for similar units\n\nA common approach: offer a renewal at 2-3% below current market rate for new leases. This rewards loyalty while keeping pace with the market.", timestamp: "2:32 PM" },
      { id: "m5", sender: "user", content: "How should I handle residents who push back on the increase?", timestamp: "2:34 PM" },
      { id: "m6", sender: "assistant", content: "Here's a negotiation framework:\n\n1. **Listen first** — Understand their specific concern (budget, value perception, competing offers)\n2. **Show the math** — Compare the increase to moving costs ($3K-5K typically)\n3. **Offer alternatives** — Shorter lease term at current rate, or longer term with a smaller increase\n4. **Highlight hidden value** — No application fees, no moving stress, established community\n5. **Know your floor** — Have a minimum acceptable rate pre-approved so your team can negotiate in real-time", timestamp: "2:34 PM" },
    ],
  },
  {
    id: "conv-2",
    title: "Maintenance turnaround time",
    preview: "How can we reduce our average work order completion time?",
    timestamp: "Mar 10, 2026 11:15 AM",
    messageCount: 4,
    tokensUsed: 1820,
    messages: [
      { id: "m7", sender: "user", content: "How can we reduce our average work order completion time? We're currently at 4.2 days.", timestamp: "11:10 AM" },
      { id: "m8", sender: "assistant", content: "4.2 days is above the industry benchmark of 2-3 days. Here are proven strategies to improve:\n\n**Triage & Prioritization**\n- Implement a priority matrix: Emergency (<4hrs), Urgent (<24hrs), Standard (<72hrs), Scheduled\n- Auto-categorize common requests to skip manual triage\n\n**Staffing & Scheduling**\n- Analyze peak request times and staff accordingly\n- Cross-train maintenance techs on common repairs\n- Consider a dedicated \"quick fix\" tech for sub-30-minute jobs\n\n**Inventory & Parts**\n- Stock common parts on-site (filters, faucet cartridges, toilet flappers)\n- Track parts usage to predict restocking needs", timestamp: "11:11 AM" },
      { id: "m9", sender: "user", content: "What metrics should we track beyond completion time?", timestamp: "11:13 AM" },
      { id: "m10", sender: "assistant", content: "Key maintenance KPIs to track:\n\n| Metric | Benchmark | Why It Matters |\n|--------|-----------|----------------|\n| First-contact resolution | >60% | Measures how often issues are fixed on the first visit |\n| Resident satisfaction | >4.2/5 | Direct quality indicator |\n| Callback rate | <10% | Shows quality of repairs |\n| Cost per work order | $150-250 | Financial efficiency |\n| Preventive vs. reactive ratio | 30:70 | Leading indicator of asset health |\n| Technician utilization | 75-85% | Staffing efficiency |", timestamp: "11:15 AM" },
    ],
  },
  {
    id: "conv-3",
    title: "Delinquency reduction strategies",
    preview: "Our delinquency rate jumped to 8.5% — what can we do?",
    timestamp: "Mar 9, 2026 4:20 PM",
    messageCount: 4,
    tokensUsed: 1650,
    messages: [
      { id: "m11", sender: "user", content: "Our delinquency rate jumped to 8.5% this month. What can we do to bring it down?", timestamp: "4:15 PM" },
      { id: "m12", sender: "assistant", content: "An 8.5% delinquency rate is concerning — the healthy benchmark is 2-4%. Here's a multi-pronged approach:\n\n**Immediate Actions (This Week)**\n- Send personalized outreach to every delinquent account, not form letters\n- Offer payment plans for residents with partial ability to pay\n- Verify all auto-pay enrollments are active\n\n**Short-Term (This Month)**\n- Launch a payment reminder campaign at 3-day, 1-day, and same-day intervals\n- Promote auto-pay enrollment with a small incentive\n- Review your late fee structure — is it motivating enough?\n\n**Long-Term (This Quarter)**\n- Implement income verification improvements in screening\n- Add alternative payment methods (cash pay networks, mobile payments)\n- Track delinquency by unit type and demographic to identify patterns", timestamp: "4:16 PM" },
      { id: "m13", sender: "user", content: "What's the best way to communicate with residents about past-due balances?", timestamp: "4:18 PM" },
      { id: "m14", sender: "assistant", content: "Communication best practices for past-due balances:\n\n1. **Be empathetic, not threatening** — \"We noticed your account has an outstanding balance\" vs. \"You are in violation of your lease\"\n2. **Multi-channel approach** — Email first, then text, then phone call\n3. **Provide clear options** — Payment portal link, phone number, office hours\n4. **Acknowledge hardship** — If applicable, mention payment plan options upfront\n5. **Set clear deadlines** — \"Please resolve by [date] to avoid additional fees\"\n\nTiming matters: Send the first reminder within 48 hours of the missed payment, not at the end of the month.", timestamp: "4:20 PM" },
    ],
  },
  {
    id: "conv-4",
    title: "Fair housing compliance",
    preview: "Can you review our screening criteria for fair housing risks?",
    timestamp: "Mar 9, 2026 10:30 AM",
    messageCount: 2,
    tokensUsed: 980,
    messages: [
      { id: "m15", sender: "user", content: "Can you help me understand the key fair housing risks in our screening criteria?", timestamp: "10:28 AM" },
      { id: "m16", sender: "assistant", content: "Here are the critical fair housing considerations for screening:\n\n**Protected Classes** (Federal: race, color, religion, national origin, sex, familial status, disability; many states add more)\n\n**Common Screening Risks:**\n- **Income requirements**: Blanket 3x rent minimums can have disparate impact. Consider alternative proof of ability to pay.\n- **Criminal history**: HUD guidance says blanket bans on criminal records violate fair housing. Use individualized assessments.\n- **Credit scores**: Hard minimums can disproportionately affect protected groups. Consider the full credit picture.\n- **Occupancy standards**: 2-per-bedroom is generally accepted; stricter standards may discriminate against families.\n\n**Best Practice**: Document your criteria, apply them consistently to all applicants, and consult with a fair housing attorney annually.", timestamp: "10:30 AM" },
    ],
  },
  {
    id: "conv-5",
    title: "Budget planning for capital improvements",
    preview: "How should I prioritize capital expenditures?",
    timestamp: "Mar 8, 2026 3:45 PM",
    messageCount: 4,
    tokensUsed: 2100,
    messages: [
      { id: "m17", sender: "user", content: "How should I prioritize capital expenditures for next year's budget?", timestamp: "3:40 PM" },
      { id: "m18", sender: "assistant", content: "Capital expenditure prioritization should follow this framework:\n\n**Tier 1 — Safety & Compliance (Must Do)**\n- Fire safety systems, structural repairs, ADA compliance\n- These are non-negotiable and should be funded first\n\n**Tier 2 — Revenue Impact (Should Do)**\n- Unit renovations that command rent premiums\n- Amenity upgrades that reduce vacancy\n- Curb appeal improvements that increase tour conversion\n\n**Tier 3 — Operational Efficiency (Nice to Have)**\n- Energy efficiency upgrades (LED, smart thermostats)\n- Technology infrastructure\n- Landscaping and common area refreshes\n\nFor each project, calculate ROI: (Annual Rent Premium × Units Affected) ÷ Project Cost = Payback Period", timestamp: "3:41 PM" },
      { id: "m19", sender: "user", content: "What's a typical budget allocation breakdown?", timestamp: "3:43 PM" },
      { id: "m20", sender: "assistant", content: "Typical capital budget allocation for multifamily:\n\n| Category | % of Budget | Examples |\n|----------|-------------|----------|\n| Unit interiors | 40-50% | Flooring, appliances, countertops, fixtures |\n| Building exterior | 15-20% | Roof, siding, parking, lighting |\n| Common areas | 10-15% | Lobby, fitness center, pool, landscaping |\n| Systems/infrastructure | 15-20% | HVAC, plumbing, electrical, elevators |\n| Technology | 5-10% | Access control, smart home, WiFi |\n\nRule of thumb: Budget $500-1,000 per unit annually for capital reserves.", timestamp: "3:45 PM" },
    ],
  },
  {
    id: "conv-6",
    title: "Prospect follow-up cadence",
    preview: "What's the ideal follow-up schedule for prospects?",
    timestamp: "Mar 8, 2026 9:00 AM",
    messageCount: 2,
    tokensUsed: 850,
    messages: [
      { id: "m21", sender: "user", content: "What's the ideal follow-up schedule for prospects after a tour?", timestamp: "8:55 AM" },
      { id: "m22", sender: "assistant", content: "Optimal prospect follow-up cadence:\n\n- **Same day**: Thank-you email with unit details and application link\n- **Day 2**: Text message checking if they have questions\n- **Day 4**: Phone call with a specific value-add (\"The unit you liked is still available\")\n- **Day 7**: Email with a limited-time incentive or alternative unit options\n- **Day 14**: Final \"still interested?\" touchpoint\n\n**Key stats**: 80% of leases are signed within 7 days of touring. After 14 days, conversion drops below 10%. Front-load your effort.", timestamp: "9:00 AM" },
    ],
  },
  {
    id: "conv-7",
    title: "Amenity ROI analysis",
    preview: "Which amenity upgrades have the best ROI?",
    timestamp: "Mar 7, 2026 2:10 PM",
    messageCount: 2,
    tokensUsed: 920,
    messages: [
      { id: "m23", sender: "user", content: "Which amenity upgrades typically have the best ROI for Class B properties?", timestamp: "2:05 PM" },
      { id: "m24", sender: "assistant", content: "Top ROI amenity upgrades for Class B multifamily:\n\n| Amenity | Typical Cost | Monthly Rent Premium | Payback |\n|---------|-------------|---------------------|----------|\n| In-unit washer/dryer | $1,500-2,000 | $75-125/mo | 16-24 months |\n| Smart locks & access | $300-500/unit | $25-40/mo | 10-18 months |\n| Package lockers | $15K-25K | $5-10/unit/mo | 18-30 months |\n| Dog park/pet amenities | $10K-30K | $25-50 pet rent | 12-24 months |\n| Fitness center refresh | $20K-50K | $15-25/unit/mo | 18-30 months |\n\n**Best bang for buck**: In-unit W/D and smart locks consistently show the fastest payback and highest resident demand.", timestamp: "2:10 PM" },
    ],
  },
  {
    id: "conv-8",
    title: "Move-in checklist optimization",
    preview: "How can we improve our move-in experience?",
    timestamp: "Mar 7, 2026 10:20 AM",
    messageCount: 2,
    tokensUsed: 780,
    messages: [
      { id: "m25", sender: "user", content: "How can we improve our move-in experience to boost early resident satisfaction?", timestamp: "10:15 AM" },
      { id: "m26", sender: "assistant", content: "A great move-in experience sets the tone for the entire residency. Here's a checklist:\n\n**Pre-Move-In (3-5 days before)**\n- Send a welcome email with move-in instructions, parking info, and elevator reservations\n- Complete the unit inspection and fix any outstanding issues\n- Place a welcome kit (community guide, local restaurant menus, small gift)\n\n**Move-In Day**\n- Have a dedicated team member greet them\n- Walk through the unit together with a condition checklist\n- Demonstrate smart home features, thermostat, appliances\n- Provide emergency maintenance contact info\n\n**First 30 Days**\n- Day 3: Check-in text asking if everything is working\n- Day 14: Invite to a community event or introduce to neighbors\n- Day 30: Satisfaction survey with a small incentive\n\nProperties with structured onboarding see 15-20% higher first-year renewal rates.", timestamp: "10:20 AM" },
    ],
  },
]

export const sampleUsageByThreshold: Record<string, UsageStats> = {
  "under-50": {
    tokensUsed: 4250,
    tokenLimit: 25000,
    percentUsed: 17,
    periodStart: "Mar 1, 2026",
    periodEnd: "Mar 31, 2026",
    conversationCount: 8,
    avgTokensPerConversation: 531,
  },
  "at-50": {
    tokensUsed: 12500,
    tokenLimit: 25000,
    percentUsed: 50,
    periodStart: "Mar 1, 2026",
    periodEnd: "Mar 31, 2026",
    conversationCount: 22,
    avgTokensPerConversation: 568,
  },
  "at-75": {
    tokensUsed: 18750,
    tokenLimit: 25000,
    percentUsed: 75,
    periodStart: "Mar 1, 2026",
    periodEnd: "Mar 31, 2026",
    conversationCount: 35,
    avgTokensPerConversation: 536,
  },
  "at-90": {
    tokensUsed: 22500,
    tokenLimit: 25000,
    percentUsed: 90,
    periodStart: "Mar 1, 2026",
    periodEnd: "Mar 31, 2026",
    conversationCount: 42,
    avgTokensPerConversation: 536,
  },
  "at-100": {
    tokensUsed: 25000,
    tokenLimit: 25000,
    percentUsed: 100,
    periodStart: "Mar 1, 2026",
    periodEnd: "Mar 31, 2026",
    conversationCount: 47,
    avgTokensPerConversation: 532,
  },
}

export const sampleUserUsage: UserUsage[] = [
  { id: "u1", name: "Sarah Johnson", email: "sjohnson@sunsetproperties.com", role: "Property Manager", property: "Sunset Apartments", tokensUsed: 8200, tokenLimit: 25000, percentUsed: 33, conversationCount: 15, lastActive: "Mar 10, 2026", status: "active" },
  { id: "u2", name: "Michael Chen", email: "mchen@sunsetproperties.com", role: "Leasing Agent", property: "Sunset Apartments", tokensUsed: 18400, tokenLimit: 25000, percentUsed: 74, conversationCount: 34, lastActive: "Mar 10, 2026", status: "active" },
  { id: "u3", name: "Jessica Williams", email: "jwilliams@sunsetproperties.com", role: "Regional Manager", property: "Oak Ridge Townhomes", tokensUsed: 22100, tokenLimit: 25000, percentUsed: 88, conversationCount: 41, lastActive: "Mar 10, 2026", status: "approaching-limit" },
  { id: "u4", name: "David Martinez", email: "dmartinez@sunsetproperties.com", role: "Maintenance Supervisor", property: "Oak Ridge Townhomes", tokensUsed: 25000, tokenLimit: 25000, percentUsed: 100, conversationCount: 47, lastActive: "Mar 9, 2026", status: "at-limit" },
  { id: "u5", name: "Emily Davis", email: "edavis@sunsetproperties.com", role: "Assistant Manager", property: "Harbor View Complex", tokensUsed: 12600, tokenLimit: 25000, percentUsed: 50, conversationCount: 23, lastActive: "Mar 10, 2026", status: "active" },
  { id: "u6", name: "Robert Taylor", email: "rtaylor@sunsetproperties.com", role: "Leasing Agent", property: "Harbor View Complex", tokensUsed: 3100, tokenLimit: 25000, percentUsed: 12, conversationCount: 6, lastActive: "Mar 8, 2026", status: "active" },
  { id: "u7", name: "Amanda Wilson", email: "awilson@sunsetproperties.com", role: "Property Manager", property: "Pine Valley Estates", tokensUsed: 19800, tokenLimit: 25000, percentUsed: 79, conversationCount: 37, lastActive: "Mar 10, 2026", status: "approaching-limit" },
  { id: "u8", name: "James Anderson", email: "janderson@sunsetproperties.com", role: "Leasing Agent", property: "Pine Valley Estates", tokensUsed: 6500, tokenLimit: 25000, percentUsed: 26, conversationCount: 12, lastActive: "Mar 9, 2026", status: "active" },
  { id: "u9", name: "Lisa Brown", email: "lbrown@sunsetproperties.com", role: "Regional Manager", property: "Maple Creek Residences", tokensUsed: 24800, tokenLimit: 25000, percentUsed: 99, conversationCount: 46, lastActive: "Mar 10, 2026", status: "approaching-limit" },
  { id: "u10", name: "Kevin Thompson", email: "kthompson@sunsetproperties.com", role: "Maintenance Tech", property: "Maple Creek Residences", tokensUsed: 1200, tokenLimit: 25000, percentUsed: 5, conversationCount: 3, lastActive: "Mar 5, 2026", status: "active" },
]

export const samplePropertyUsage: PropertyUsage[] = [
  { id: "p1", name: "Sunset Apartments", totalTokensUsed: 26600, totalTokenLimit: 50000, percentUsed: 53, userCount: 5, activeUsers: 4, conversationCount: 49 },
  { id: "p2", name: "Oak Ridge Townhomes", totalTokensUsed: 47100, totalTokenLimit: 50000, percentUsed: 94, userCount: 4, activeUsers: 3, conversationCount: 88 },
  { id: "p3", name: "Harbor View Complex", totalTokensUsed: 15700, totalTokenLimit: 50000, percentUsed: 31, userCount: 6, activeUsers: 4, conversationCount: 29 },
  { id: "p4", name: "Pine Valley Estates", totalTokensUsed: 26300, totalTokenLimit: 50000, percentUsed: 53, userCount: 3, activeUsers: 3, conversationCount: 49 },
  { id: "p5", name: "Maple Creek Residences", totalTokensUsed: 26000, totalTokenLimit: 50000, percentUsed: 52, userCount: 4, activeUsers: 2, conversationCount: 49 },
]

export const sampleClientUsage: ClientUsage = {
  id: "c1",
  name: "Sunset Property Group",
  totalTokensUsed: 141700,
  totalTokenLimit: 250000,
  percentUsed: 57,
  propertyCount: 5,
  userCount: 22,
  conversationCount: 264,
  properties: samplePropertyUsage,
}

export const sampleAuditConversations: AuditConversation[] = [
  {
    id: "audit-1",
    userId: "u3",
    userName: "Jessica Williams",
    userEmail: "jwilliams@sunsetproperties.com",
    property: "Oak Ridge Townhomes",
    title: "Eviction process guidance",
    messageCount: 6,
    tokensUsed: 3200,
    startedAt: "Mar 10, 2026 9:15 AM",
    lastMessageAt: "Mar 10, 2026 9:28 AM",
    flagged: true,
    flagReason: "Legal topic — eviction procedures",
    messages: [
      { id: "a1", sender: "user", content: "What's the proper eviction process in Utah?", timestamp: "9:15 AM" },
      { id: "a2", sender: "assistant", content: "Here's an overview of the Utah eviction process. Note: Always consult with your legal team for specific cases.\n\n1. **Serve proper notice** — 3-day pay or quit for nonpayment, 15-day notice for lease violations\n2. **File with the court** — If the tenant doesn't comply, file an eviction complaint with the district court\n3. **Court hearing** — Typically scheduled within 10 days\n4. **Judgment and order of restitution** — If the court rules in your favor\n5. **Sheriff enforcement** — Only law enforcement can physically remove a tenant\n\n**Important**: Never attempt self-help eviction (changing locks, removing belongings, shutting off utilities). This is illegal in Utah.", timestamp: "9:16 AM" },
      { id: "a3", sender: "user", content: "What if the tenant claims discrimination?", timestamp: "9:20 AM" },
      { id: "a4", sender: "assistant", content: "If a tenant raises a discrimination claim during eviction:\n\n1. **Document everything** — Ensure your eviction reason is clearly documented with dates and evidence\n2. **Consistent treatment** — Show that you apply the same policies to all residents\n3. **Pause and consult** — Contact your legal counsel immediately before proceeding\n4. **Preserve records** — Keep all communication, notices, and payment history\n\nThis is a situation where legal counsel is essential. I'd recommend looping in your attorney before taking the next step.", timestamp: "9:21 AM" },
      { id: "a5", sender: "user", content: "How long does the whole process typically take?", timestamp: "9:25 AM" },
      { id: "a6", sender: "assistant", content: "Typical Utah eviction timeline:\n\n- **Notice period**: 3-15 days (depending on reason)\n- **Court filing to hearing**: 7-10 days\n- **Hearing to judgment**: Same day to 3 days\n- **Order of restitution**: 3 days after judgment\n- **Total**: 2-5 weeks minimum\n\nDelays can occur if the tenant contests, requests a continuance, or files an appeal. Budget 4-8 weeks for contested evictions.", timestamp: "9:28 AM" },
    ],
  },
  {
    id: "audit-2",
    userId: "u2",
    userName: "Michael Chen",
    userEmail: "mchen@sunsetproperties.com",
    property: "Sunset Apartments",
    title: "Crafting lease addendum language",
    messageCount: 4,
    tokensUsed: 1800,
    startedAt: "Mar 9, 2026 3:40 PM",
    lastMessageAt: "Mar 9, 2026 3:52 PM",
    flagged: false,
    messages: [
      { id: "a7", sender: "user", content: "Can you help me draft language for a pet policy addendum?", timestamp: "3:40 PM" },
      { id: "a8", sender: "assistant", content: "Here's sample pet policy addendum language:\n\n**PET ADDENDUM**\n\nThis addendum is attached to and made part of the Lease Agreement dated ___.\n\nResident is permitted to keep the following pet(s) on the premises:\n- Type: ___\n- Breed: ___\n- Weight: ___\n- Name: ___\n\n**Terms:**\n1. A non-refundable pet fee of $___  and monthly pet rent of $___ applies\n2. Pet must be current on vaccinations (proof required annually)\n3. Resident is responsible for all damages caused by the pet\n4. Pet must be leashed in all common areas\n5. Resident must immediately clean up after the pet\n6. Management reserves the right to revoke pet privileges for violations\n\n*Note: This is sample language. Have your legal team review before use.*", timestamp: "3:42 PM" },
      { id: "a9", sender: "user", content: "Should we include breed restrictions?", timestamp: "3:48 PM" },
      { id: "a10", sender: "assistant", content: "Breed restrictions are a business decision with legal implications:\n\n**Arguments for restrictions:**\n- Insurance requirements may mandate them\n- Liability reduction for aggressive breed incidents\n\n**Arguments against:**\n- Growing legal pushback in some jurisdictions\n- Reduces your applicant pool\n- Breed identification is subjective and often inaccurate\n- Some states/cities have banned breed-specific legislation\n\n**Recommended approach:** Focus on behavior-based policies rather than breed bans. Require weight limits if needed, and mandate renter's insurance with liability coverage for all pet owners. Check your insurance policy requirements — they may dictate your options.", timestamp: "3:52 PM" },
    ],
  },
  {
    id: "audit-3",
    userId: "u4",
    userName: "David Martinez",
    userEmail: "dmartinez@sunsetproperties.com",
    property: "Oak Ridge Townhomes",
    title: "HVAC troubleshooting guide",
    messageCount: 4,
    tokensUsed: 1500,
    startedAt: "Mar 9, 2026 11:00 AM",
    lastMessageAt: "Mar 9, 2026 11:12 AM",
    flagged: false,
    messages: [
      { id: "a11", sender: "user", content: "Can you give me a quick HVAC troubleshooting checklist for common tenant complaints?", timestamp: "11:00 AM" },
      { id: "a12", sender: "assistant", content: "HVAC Troubleshooting Quick Reference:\n\n**\"AC not cooling\"**\n1. Check thermostat settings (cool mode, correct temp)\n2. Check/replace air filter\n3. Verify breaker isn't tripped\n4. Check if outdoor unit fan is running\n5. Look for ice on refrigerant lines\n\n**\"Heater not working\"**\n1. Check thermostat (heat mode, temp above room temp)\n2. Check/replace filter\n3. Verify pilot light (gas) or breaker (electric)\n4. Check for blocked vents\n\n**\"Strange noises\"**\n- Rattling: Loose panel or debris\n- Squealing: Belt or motor bearing\n- Clicking: Relay or electrical issue\n- Banging: Compressor issue (call HVAC tech)", timestamp: "11:02 AM" },
      { id: "a13", sender: "user", content: "When should we call a licensed HVAC tech vs handling in-house?", timestamp: "11:08 AM" },
      { id: "a14", sender: "assistant", content: "**Handle in-house:**\n- Filter replacement\n- Thermostat issues/replacement\n- Breaker resets\n- Vent cleaning/unblocking\n- Condensate drain clearing\n\n**Call a licensed tech:**\n- Refrigerant issues (requires EPA certification)\n- Compressor problems\n- Electrical component failures\n- Gas line or heat exchanger concerns\n- Any issue involving refrigerant handling\n- System not responding to basic troubleshooting\n\n**Rule of thumb**: If it involves refrigerant, gas, or major electrical components, always call a licensed tech. The liability risk isn't worth the savings.", timestamp: "11:12 AM" },
    ],
  },
]

export const aiResponsePool: string[] = [
  "Great question! Based on industry best practices for multifamily operations:\n\n1. **Start with data** — Review your current metrics before making changes. Baseline everything.\n2. **Benchmark against peers** — Compare your performance to similar properties in your market.\n3. **Set incremental goals** — Aim for 5-10% improvements quarter over quarter rather than dramatic shifts.\n4. **Track consistently** — Use the same methodology each period for accurate trending.\n\nThe properties seeing the best results are the ones that iterate quickly and measure everything. Would you like me to dive deeper into any of these areas?",

  "Here's what I'd recommend based on multifamily operations best practices:\n\n**Immediate actions:**\n- Audit your current process end-to-end and document pain points\n- Identify the top 3 bottlenecks causing delays\n- Implement quick wins first — usually communication and timing improvements\n\n**Longer term:**\n- Invest in automation where manual handoffs create delays\n- Cross-train your team so no single person is a bottleneck\n- Review results monthly and adjust your approach\n\nConsistency is key. Even small improvements compound over time when applied systematically.",

  "This is a common challenge across the industry. Here's a structured approach:\n\n| Priority | Action | Expected Impact | Timeline |\n|----------|--------|-----------------|----------|\n| High | Streamline communication flow | 15-20% faster | 1-2 weeks |\n| High | Standardize templates/checklists | Reduce errors by 30% | 1 week |\n| Medium | Automate status notifications | Save 2-3 hrs/week | 2-4 weeks |\n| Medium | Implement SLA tracking | Visibility + accountability | 2 weeks |\n| Low | Vendor portal integration | Long-term efficiency | 1-2 months |\n\nI'd suggest starting with the high-priority items — they'll give you the fastest ROI and build momentum for the larger initiatives.",

  "There are several factors to consider here:\n\n**Market dynamics:**\n- Your submarket's supply/demand balance matters most. Check new deliveries within a 3-mile radius.\n- Seasonal patterns affect pricing power — spring/summer typically stronger for new leases.\n- Employment trends in your area directly correlate with demand.\n\n**Operational levers:**\n- Concession strategy: Are you offering concessions? If so, what's the net effective rent?\n- Renewal spread: How do your renewal rates compare to new lease rates?\n- Loss-to-lease: What's the gap between your current rents and market?\n\n**The bottom line:** Properties that monitor these metrics weekly (not monthly) can adjust pricing 2-3 weeks faster than competitors, which translates to 1-2% higher revenue over time.",

  "Absolutely — this is an area where most operators have room for improvement. Here's a framework:\n\n**Communication cadence:**\n- Day 1: Acknowledgment + expected timeline\n- Day 3: Status update (even if \"still in progress\")\n- Day 5+: Proactive update every 2 days until resolved\n- Completion: Follow-up satisfaction check within 24 hours\n\n**Channel preferences:**\n- Text/SMS: Best for quick updates (85% open rate within 5 minutes)\n- Email: Best for detailed information, documentation, policy changes\n- In-app: Best for ongoing status tracking and self-service\n- Phone: Reserve for urgent/sensitive matters\n\n**Pro tip:** Residents who feel informed are 40% less likely to leave negative reviews, even when the underlying issue takes longer to resolve. Communication quality matters more than speed in most cases.",

  "Good thinking — this is worth analyzing carefully. Here's the data-driven approach:\n\n**Step 1: Calculate your true cost**\n- Vacancy loss: Average monthly rent × days vacant ÷ 30\n- Turn cost: Labor + materials + lost rent during make-ready\n- Leasing cost: Marketing + staff time + concessions for new lease\n- Total turnover cost typically runs $3,000-$5,000 per unit\n\n**Step 2: Compare to retention cost**\n- Renewal concession or reduced increase: Usually $50-150/month difference\n- Retention incentive: One-time $200-500 gift card or upgrade\n- Annual cost of retention: Far less than turnover in almost every case\n\n**Step 3: Break-even analysis**\n- If your renewal offer is $100/month below market: $1,200/year\n- If turnover costs $4,000: You break even in 3+ years\n- Most residents stay 2-3 years, making moderate retention offers almost always profitable\n\nWould you like me to run the specific numbers for your property?",

  "Let me walk you through the key considerations:\n\n1. **Compliance first** — Always ensure you're meeting federal, state, and local requirements. This is non-negotiable and should be reviewed quarterly with legal counsel.\n\n2. **Documentation** — Every decision, interaction, and policy should be documented. If it's not written down, it didn't happen (from a legal perspective).\n\n3. **Consistency** — Apply policies uniformly across all residents and prospects. Inconsistency is the #1 risk factor for complaints.\n\n4. **Training** — Your team should complete annual training. New hires should complete it within their first 30 days.\n\n5. **Reasonable accommodations** — Have a clear, well-documented process. Response time matters — the industry standard is acknowledging requests within 3 business days.\n\n**Important:** This is general guidance, not legal advice. For specific situations, always consult with your legal team or a specialist in your jurisdiction.",

  "Here's a comprehensive look at what the data tells us:\n\n**Key performance indicators to track:**\n- **Response time**: Industry benchmark is under 24 hours for non-emergency requests\n- **Resolution time**: Target 2-3 days for standard items, same-day for emergencies\n- **First-time fix rate**: Best-in-class is >70%\n- **Resident satisfaction**: Target 4.2+ out of 5\n- **Cost per service**: Track by category to identify outliers\n\n**Common patterns we see:**\n- Properties with preventive maintenance programs have 25-35% fewer emergency requests\n- Mobile-first work order submission increases reporting by 40%\n- Automated routing to the right technician cuts resolution time by ~30%\n\n**Quick win:** If you're not already doing it, implement a post-completion satisfaction survey (1-2 questions, takes 10 seconds). The response data is invaluable for identifying systemic issues before they become major problems.",

  "That's a smart question — optimizing this can have a significant impact on your bottom line. Here's what top-performing properties do:\n\n**Pre-planning (30 days before):**\n- Review lease expiration schedule and prioritize renewals\n- Run market comps to determine fair renewal pricing\n- Prepare personalized renewal packages\n\n**Execution (send 90-120 days before expiration):**\n- **Tier 1 offer**: Best rate for immediate commitment (within 14 days)\n- **Tier 2 offer**: Standard rate with 30-day decision window\n- **Multiple term options**: 6, 12, 15, and 18-month options at different price points\n\n**Follow-up cadence:**\n- Day 1: Send renewal offer via email + in-app notification\n- Day 7: Text message reminder if no response\n- Day 14: Phone call from property manager\n- Day 21: Final offer with deadline\n- Day 30: Notice-to-vacate reminder if no renewal signed\n\n**Result:** Properties following this structured approach see 8-12% higher renewal rates than those with ad-hoc processes.",

  "This is an area where I see a lot of opportunity for most operators. Let me break it down:\n\n**Budget allocation framework:**\n- 60% to revenue-generating improvements (unit upgrades, amenities that command premium)\n- 25% to asset preservation (roof, HVAC, plumbing — things that prevent catastrophic cost)\n- 15% to operational efficiency (technology, energy savings, process improvements)\n\n**ROI calculation for each project:**\n```\nAnnual Benefit = (Monthly Rent Premium × Units Affected × 12) + Annual Cost Savings\nPayback Period = Project Cost ÷ Annual Benefit\nTarget: Payback within 18-24 months for discretionary improvements\n```\n\n**Top ROI upgrades for 2026:**\n1. Smart locks + access control: 10-18 month payback\n2. In-unit washer/dryer: 16-24 month payback\n3. Energy-efficient appliances: 24-36 month payback (+ ESG benefit)\n4. Package management system: 18-30 month payback\n5. Common area refresh: Harder to quantify but impacts vacancy/tour conversion\n\nThe key is prioritizing projects with the shortest payback period first, then reinvesting those returns into longer-horizon improvements.",

  "Excellent question — resident retention is one of the highest-leverage areas in property management. Here are proven strategies:\n\n**Relationship building:**\n- Host quarterly community events (cost: $500-1,000; ROI: reduces turnover by 5-10%)\n- Implement a resident ambassador program for long-tenured residents\n- Personal touchpoints: birthday cards, move-in anniversaries\n\n**Service excellence:**\n- Same-day response to maintenance requests (even if resolution takes longer)\n- Proactive maintenance: Fix things before residents report them\n- Annual unit walk-through to identify and address issues early\n\n**Value perception:**\n- Regular communication about property improvements\n- Transparent rent increase justification tied to market data and improvements\n- Loyalty perks for 2+ year residents (free carpet cleaning, parking upgrade, etc.)\n\n**Data point:** The cost of replacing a resident is typically $3,000-5,000. Every 1% improvement in retention rate can save $15,000-50,000 annually depending on property size. The math almost always favors retention investment over acquisition.",

  "Let me give you a data-driven perspective on this:\n\n**Current market context:**\n- National vacancy rates: ~6% (varies significantly by submarket)\n- Rent growth has moderated to 2-3% year-over-year nationally\n- New supply continues in many Sun Belt markets, creating competitive pressure\n\n**What this means for your strategy:**\n- **Pricing**: Be competitive but don't race to the bottom. Focus on value-add differentiation.\n- **Concessions**: If offering, track net effective rent vs. face rate religiously\n- **Marketing**: Shift budget to digital channels — 75%+ of prospects start their search online\n\n**Tactical recommendations:**\n1. Update unit photos and virtual tours quarterly\n2. Respond to all online reviews within 24 hours (positive and negative)\n3. Track lead-to-tour and tour-to-lease conversion rates weekly\n4. A/B test your listing descriptions — small changes can improve click-through by 15-20%\n\nMarkets where operators stay data-driven and responsive tend to outperform peers by 3-5% on revenue per available unit, even in challenging environments.",
]

export const suggestedPrompts = [
  "How can I improve resident retention at my property?",
  "What's the best approach to handling late rent payments?",
  "Help me understand fair housing requirements for screening",
  "What amenity upgrades have the best ROI?",
]

export const sampleBetaOverview: BetaOverview = {
  totalClients: 8,
  totalTokensAllocated: 1_050_000,
  totalTokensUsed: 623_400,
  percentUsed: 59,
  clientsAtLimit: 1,
  clientsApproaching: 2,
  avgUtilization: 59,
  allotmentChangesThisWeek: 3,
}

export const sampleBetaClients: BetaClient[] = [
  {
    id: "bc1",
    name: "Sunset Property Group",
    plan: "beta-large",
    tokenAllotment: 250_000,
    tokensUsed: 141_700,
    percentUsed: 57,
    propertyCount: 5,
    userCount: 22,
    activeUsers: 18,
    conversationCount: 264,
    avgTokensPerUser: 7_872,
    topUsageProperty: "Oak Ridge Townhomes",
    enrolledDate: "Feb 1, 2026",
    lastActive: "Mar 10, 2026",
    feedbackScore: 4.2,
    status: "healthy",
    allotmentHistory: [
      { id: "ah1", timestamp: "Feb 1, 2026 10:00 AM", changedBy: "Caleb Harris", previousLimit: 0, newLimit: 100_000, reason: "Initial beta enrollment — 5 properties, 22 users", level: "client", targetName: "Sunset Property Group" },
      { id: "ah2", timestamp: "Feb 15, 2026 2:30 PM", changedBy: "Caleb Harris", previousLimit: 100_000, newLimit: 150_000, reason: "Client reported heavy usage on leasing workflows. Increasing to avoid throttling during peak season.", level: "client", targetName: "Sunset Property Group" },
      { id: "ah3", timestamp: "Mar 1, 2026 9:15 AM", changedBy: "Natalie Park", previousLimit: 150_000, newLimit: 250_000, reason: "Month 2 review — utilization at 92%. Client expanding to all properties. Large increase to accommodate full rollout.", level: "client", targetName: "Sunset Property Group" },
    ],
  },
  {
    id: "bc2",
    name: "Greystar Real Estate Partners",
    plan: "beta-large",
    tokenAllotment: 200_000,
    tokensUsed: 187_600,
    percentUsed: 94,
    propertyCount: 8,
    userCount: 35,
    activeUsers: 28,
    conversationCount: 412,
    avgTokensPerUser: 6_700,
    topUsageProperty: "The Metropolitan",
    enrolledDate: "Feb 1, 2026",
    lastActive: "Mar 10, 2026",
    feedbackScore: 4.5,
    status: "critical",
    allotmentHistory: [
      { id: "ah4", timestamp: "Feb 1, 2026 10:00 AM", changedBy: "Caleb Harris", previousLimit: 0, newLimit: 100_000, reason: "Initial beta enrollment — strategic partner, 8 properties", level: "client", targetName: "Greystar Real Estate Partners" },
      { id: "ah5", timestamp: "Feb 20, 2026 4:00 PM", changedBy: "Caleb Harris", previousLimit: 100_000, newLimit: 200_000, reason: "Extremely high adoption. Leasing teams using it daily for prospect follow-ups and market comps.", level: "client", targetName: "Greystar Real Estate Partners" },
    ],
  },
  {
    id: "bc3",
    name: "Avenue5 Residential",
    plan: "beta-medium",
    tokenAllotment: 150_000,
    tokensUsed: 98_200,
    percentUsed: 65,
    propertyCount: 4,
    userCount: 14,
    activeUsers: 11,
    conversationCount: 178,
    avgTokensPerUser: 8_927,
    topUsageProperty: "Cascade Pointe",
    enrolledDate: "Feb 10, 2026",
    lastActive: "Mar 10, 2026",
    feedbackScore: 3.8,
    status: "healthy",
    allotmentHistory: [
      { id: "ah6", timestamp: "Feb 10, 2026 11:00 AM", changedBy: "Natalie Park", previousLimit: 0, newLimit: 100_000, reason: "Initial beta enrollment — mid-size operator, 4 properties", level: "client", targetName: "Avenue5 Residential" },
      { id: "ah7", timestamp: "Mar 5, 2026 10:30 AM", changedBy: "Natalie Park", previousLimit: 100_000, newLimit: 150_000, reason: "Moderate increase — usage healthy but growing. Client wants to add maintenance team.", level: "client", targetName: "Avenue5 Residential" },
    ],
  },
  {
    id: "bc4",
    name: "Pinnacle Property Management",
    plan: "beta-small",
    tokenAllotment: 50_000,
    tokensUsed: 48_900,
    percentUsed: 98,
    propertyCount: 2,
    userCount: 6,
    activeUsers: 5,
    conversationCount: 92,
    avgTokensPerUser: 9_780,
    topUsageProperty: "Summit Ridge",
    enrolledDate: "Feb 15, 2026",
    lastActive: "Mar 10, 2026",
    feedbackScore: 4.7,
    status: "exhausted",
    allotmentHistory: [
      { id: "ah8", timestamp: "Feb 15, 2026 2:00 PM", changedBy: "Caleb Harris", previousLimit: 0, newLimit: 50_000, reason: "Initial beta enrollment — small operator, 2 properties, testing power-user adoption", level: "client", targetName: "Pinnacle Property Management" },
    ],
  },
  {
    id: "bc5",
    name: "BH Management Services",
    plan: "beta-large",
    tokenAllotment: 150_000,
    tokensUsed: 62_100,
    percentUsed: 41,
    propertyCount: 6,
    userCount: 18,
    activeUsers: 9,
    conversationCount: 115,
    avgTokensPerUser: 6_900,
    topUsageProperty: "Riverside Commons",
    enrolledDate: "Feb 10, 2026",
    lastActive: "Mar 9, 2026",
    feedbackScore: 3.5,
    status: "healthy",
    allotmentHistory: [
      { id: "ah9", timestamp: "Feb 10, 2026 11:00 AM", changedBy: "Natalie Park", previousLimit: 0, newLimit: 150_000, reason: "Initial beta enrollment — large operator but conservative rollout", level: "client", targetName: "BH Management Services" },
    ],
  },
  {
    id: "bc6",
    name: "Lincoln Property Company",
    plan: "beta-medium",
    tokenAllotment: 100_000,
    tokensUsed: 34_200,
    percentUsed: 34,
    propertyCount: 3,
    userCount: 10,
    activeUsers: 6,
    conversationCount: 64,
    avgTokensPerUser: 5_700,
    topUsageProperty: "Lincoln Tower",
    enrolledDate: "Feb 20, 2026",
    lastActive: "Mar 8, 2026",
    feedbackScore: null,
    status: "healthy",
    allotmentHistory: [
      { id: "ah10", timestamp: "Feb 20, 2026 3:00 PM", changedBy: "Caleb Harris", previousLimit: 0, newLimit: 100_000, reason: "Initial beta enrollment — 3 properties, mid-tier adoption expected", level: "client", targetName: "Lincoln Property Company" },
    ],
  },
  {
    id: "bc7",
    name: "RPM Living",
    plan: "beta-small",
    tokenAllotment: 75_000,
    tokensUsed: 31_400,
    percentUsed: 42,
    propertyCount: 2,
    userCount: 8,
    activeUsers: 5,
    conversationCount: 58,
    avgTokensPerUser: 6_280,
    topUsageProperty: "Vista Park",
    enrolledDate: "Feb 25, 2026",
    lastActive: "Mar 10, 2026",
    feedbackScore: 4.0,
    status: "healthy",
    allotmentHistory: [
      { id: "ah11", timestamp: "Feb 25, 2026 1:00 PM", changedBy: "Natalie Park", previousLimit: 0, newLimit: 50_000, reason: "Initial beta enrollment — small test cohort", level: "client", targetName: "RPM Living" },
      { id: "ah12", timestamp: "Mar 8, 2026 11:00 AM", changedBy: "Caleb Harris", previousLimit: 50_000, newLimit: 75_000, reason: "Good early adoption, increasing allotment to avoid near-term cap", level: "client", targetName: "RPM Living" },
    ],
  },
  {
    id: "bc8",
    name: "Cortland",
    plan: "beta-medium",
    tokenAllotment: 75_000,
    tokensUsed: 19_300,
    percentUsed: 26,
    propertyCount: 3,
    userCount: 9,
    activeUsers: 4,
    conversationCount: 36,
    avgTokensPerUser: 4_825,
    topUsageProperty: "Cortland Estates",
    enrolledDate: "Mar 1, 2026",
    lastActive: "Mar 9, 2026",
    feedbackScore: null,
    status: "healthy",
    allotmentHistory: [
      { id: "ah13", timestamp: "Mar 1, 2026 10:00 AM", changedBy: "Caleb Harris", previousLimit: 0, newLimit: 75_000, reason: "Initial beta enrollment — newest cohort, 3 properties", level: "client", targetName: "Cortland" },
    ],
  },
]
